feature:
  - head-branch: 
    - '/^feat(ure)?_.+/'

enhancement:
  - head-branch:
    - '/^enhancement_.+/'
    - '/^improve_.+/'
    - '/^revise_.+/'

bug:
  - head-branch:
    - '/^fix_.+/'

refactor:
  - head-branch:
    - '/^refactor(ing)?_.+/'

documentation:
  - head-branch:
    - '/^doc(umentation)?_.+/'

chore:
  - head-branch:
    - '/^chore_.+/'
