name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 機能追加・アップデート'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 バグ修正'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: feature
    branch:
      - '/^feat(ure)?_.+/'
  - label: bug
    branch:
      - '/^fix_.+/'
  - label: chore
    branch:
      - '/^chore_.+/'
  - label: refactor
    branch:
      - '/(refactor|refactoring)_.+/'
  - label: documentation
    branch:
      - '/doc(umentation)_.+/'
    files:
      - '*.md'
  - label: enhancement
    branch:
      - '/(enhancement|improve)_.+/'
template: |
  ## Changes

  $CHANGES