name: Auto Merge

on:
  workflow_run:
    workflows:
      - Release Drafter
    types: 
      - completed
    branches-ignore:
      - master

jobs:
  check_suite_complete:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call pre merge check
        run: echo "Triggered by Workflow Completed"