name: PR Auto Create

on:
  push:
    branches-ignore:
      - master

jobs:
  check_pr_existence:
    runs-on: ubuntu-latest
    outputs:
      pr_exists: ${{ steps.check_if_pr_exists.outputs.pr_exists }}

    steps:
      - name: Check if PR already exists
        id: check_if_pr_exists
        run: |
          PR_EXISTS=$(gh pr list --base master --head ${{ github.ref_name }} --repo ${{ github.repository }} | wc -l)
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_pull_request:
    needs: check_pr_existence
    if: needs.check_pr_existence.outputs.pr_exists == 0
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Create PR
        id: create_pull_request
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          PREPOSITIONS="For|In|To|With|On|At|From|By|About|As|Into|Like|Through|After|Over|Between|Out|Against|During|Without|Before|Under|Around|Among"
          # 最初の単語を特別扱いするために抽出し、括弧を追加
          PREFIX=$(echo $BRANCH_NAME | sed -r "s/^([a-z]+)_.*$/\1/")
          # 残りの文字列を整形
          REMAINING_TITLE=$(echo $BRANCH_NAME | sed -r "s/^[a-z]+_(.*)$/\1/; s/_/ /g; s/\b([a-z])/\u\1/g; s/\b($PREPOSITIONS)\b/\L\1/g")
          PR_URL=$(gh pr create --base master \
            --head ${{ github.ref }} \
            --title "[$PREFIX] $REMAINING_TITLE" \
            --body "This PR was automatically created by the PR Auto Create workflow."  \
            --repo ${{ github.repository }})
          PR_NUMER=$(echo $PR_URL | sed -r "s/.*\/pull\/([0-9]+)/\1/")
          echo $PR_NUMBER
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT

        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Label PR
        uses: actions/labeler@v5
        with:
          pr-number: ${{ steps.create_pull_request.outputs.pr_number }}
