name: Deploy

on:
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do Something
        run: echo "Do Something"

      - name: Notify
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "アップデートがリリースされました。アップデート内容は以下のとおりです。\n\n${{ github.event.pull_request.body }}"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
