name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do Something
        run: echo "Do Something"

  notify:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check URL
        run: echo ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "Deployment complete!"}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
