name: Auto Labeler

on:
  workflow_run:
    workflows:
      - PR Auto Create
    types: 
      - completed
    branches-ignore:
      - master

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Get PR number
        id: get-pr
        run: |
          echo "PR_NUMBER=$(jq --raw-output '.workflow_run.pull_requests[0].number' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Chckeout code
        uses: actions/checkout@v4

      - name: Labeling
        uses: actions/labeler@v5
