name: Auto Labeler

on:
  workflow_run:
    workflows:
      - PR Auto Create
    types: 
      - completed
    branches-ignore:
      - master

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Chckeout code
        uses: actions/checkout@v4

      - name: Labeling
        uses: actions/labeler@v5
