name: Pre Merge Check

on:
  pull_request:
    branches:
      - master

jobs:
  pre_merge_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do Pre Merge Check
        run: echo "Do Pre Merge Check"

      - name: echo
        run: |
          echo "${{ github.event.pull_request.title }}"
          echo "アップデートがリリースされました。アップデート内容は以下のとおりです。\n\n${{ github.event.pull_request.body }}"
          echo "${{ github.event.pull_request }}"
