name: Pre Merge Check

on:
  pull_request:
    branches:
      - master

jobs:
  pre_merge_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do Pre Merge Check
        run: echo "Do Pre Merge Check"

      - name: Notify
        run: |
          BODY="${{ github.event.pull_request.body }}"
          echo $BODY
          echo "*******************************"
          MESSAGE=$"アップデートがリリースされました。\n\nアップデート内容は以下のとおりです。$BODY"
          echo $MESSAGE
          echo "*******************************"
          JSON=$(jq -n --arg msg "$MESSAGE" '{content: $msg}')
          echo $JSON
          echo "${{ github.event.pull_request }}"
          curl -X POST -H "Content-Type: application/json" \
            -d "$JSON" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
