name: Pre Merge Check

on:
  pull_request:
    branches:
      - master

jobs:
  pre_merge_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Do Pre Merge Check
        run: echo "Do Pre Merge Check"

  call_deploy:
    needs: pre_merge_check
    runs-on: ubuntu-latest
    steps:
      - name: Call deploy
        uses: ./.github/workflows/deploy.yml
