name: Release Triggered Deploy

on:
  release:
    types: [published]

jobs:
  pre-deployment-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Execute Pre Deployment Script
        run: echo "Executing Pre Deployment Script"

      - name: Returns Result
        run: exit 0

  deploy:
    needs: pre-deployment-check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Do Something
        run: echo "Exec Deploy Script"

      - name: Notify to Discord
        run: |
          RELEASE_NOTE="${{ github.event.release.body }}"
          MESSAGE=$'サービスがアップデートされました。\nアップデート内容は以下です。\n\n'$RELEASE_NOTE
          JSON=$(jq -n --arg msg "$MESSAGE" '{content: $msg}')
          curl -X POST -H "Content-Type: application/json" -d "$JSON" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

  notify-failure:
    needs: pre-deployment-check
    if: ${{ failure()}}
    runs-on: ubuntu-latest

    steps:
      - name: Notify to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "Deployment failed."}' \
            ${{ secrets.DISCORD_WEBHOOK_URL }}